Vagrant.configure('2') do |config|
  config.vm.box = 'mvbcoding/awslinux'

  config.vm.define :app do |host|
    host.vm.network 'private_network', ip: '192.168.34.10'
    host.vm.hostname = 'app'
  end

  config.vm.define :aggregator do |host|
    host.vm.network 'private_network', ip: '192.168.34.11'
    host.vm.hostname = 'aggregator'
  end
end
